### PR TITLE
Fix link to desktop example image.

### PR DESCRIPTION
**Pull request by grug**
I just saw that the example link is linking to the wrong image so I thought I'd fix that up!

Sorry about the line ending at the end of the file being added in the commit - I blame OSX.

### CODE REVIEW

**Comment by grug** [comment]
I also enabled CORS in the server as that is pretty handy for local development.

**Comment by damnhipster** [comment]
Yes, but that may be part of the test ;)

**Comment by thearegee** [comment]
hey @grug thanks for this, I just noticed the desktop error thanks for fixing it.

Just thinking about the CORS work, I'm happy to include the headers, it was never intentionally part of the test. However where it's set means it will be applied to all requests. Does it make sense to apply this to the HTML?

**Comment by grug** [comment]
Hey @thearegee - I think given the scope of the current test that it would be fine to enable it for all requests. Obviously it's not really applicable to the route that's serving up the index page. You could set up middleware that only applies the CORS headers to the API routes that need to get hit for the tech testing purposes (i.e. `/api/products` and `/api/product/$id`). It wouldn't be too hard to make it configurable so that if any new routes are added in the future (if the requirements of the tech test change), they can also have the CORS headers applied to them, too.

**Comment by thearegee** [comment]
Yeah I think you are right, as this is for a technical test based more around the building customer experiences and not a production server I'm happy to apply this change.

Thanks for doing this :)

**Comment by grug** [comment]
No worries - thanks for merging it :)

**Pull request merged**
